[Kafka]
auto.offset.reset=earliest
bootstrap.servers=localhost:9092

[inputs]
# Kafka poll timeout in milliseconds.
timeoutMS=100
# Retry interval in minutes.
retry.period.min=0.05
# Mode of program. (limited or unlimited
retry.mode=unlimited
# Retry count for failed operations.
retry.count=5
# Specifies how often (in minutes) the merge thread should run.
merge.thread.interval.minutes=0.1
# Determines at what intervals to check the topic list.
check.topics.interval.minutes=60